auto_resume: False

cudnn_benchmark: True
cudnn_deterministic: False
cudnn_enabled: True

data_dir: ""
gpus: [0, 1, 2, 3]
output_dir: "output"
log_dir: "log"
workers: "8x"
print_freq: 30

model:
  image_size: [256, 192]
  heatmap_size: [64, 48]
  init_weights: True
  name: pose_hrnet
  num_joints: 17
  pretrained: ./pretrained/hrnet_w32_256x192.pth
  sigma: 2
  type: simple
  tag_per_joint: True
  target_type: gaussian
  use_featuremap: True
  return_hoe: False

  extra:
    final_conv_kernel: 1
    pretrained_layers: ["*"]
    stage2:
      block: BASIC
      fuse_method: SUM
      num_blocks: [4, 4]
      num_channels: [32, 64]
      num_branches: 2
      num_modules: 1
    stage3:
      block: BASIC
      fuse_method: SUM
      num_blocks: [4, 4, 4]
      num_channels: [32, 64, 128]
      num_branches: 3
      num_modules: 4
    stage4:
      block: BASIC
      fuse_method: SUM
      num_blocks: [4, 4, 4, 4]
      num_channels: [32, 64, 128, 256]
      num_branches: 4
      num_modules: 3
loss_use_different_joints_weight: False
loss_use_target_weight: True

debug_debug: True
debug_save_batch_images_gt: True
debug_save_batch_images_pred: True
debug_save_heatmaps_gt: True
debug_save_heatmaps_pred: True
